module002/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, DateTimeField, SelectField, HiddenField, TextAreaField, SubmitField
from wtforms.validators import InputRequired, Length
from wtforms.fields.html5 import DateField, TimeField, DateTimeLocalField
import datetime


class PostForm(FlaskForm):
    body = TextAreaField("What's on your mind?")

module002/views.py
from flask import Blueprint, render_template, abort, flash, redirect, url_for, request
from models import get_db, User, Course, Post, Follow
from flask_login import login_required, current_user

from module002.forms import *

module002 = Blueprint("module002", __name__,static_folder="static",template_folder="templates")

db = get_db()

@module002.route('/')
@login_required
def module002_index():
    if current_user.profile in ('admin','staff','student'):
        follows = Follow.query.filter_by(user_id=current_user.id)
        return render_template("module002_index.html",module="module002", routes=follows)
    else:
        flash("Access denied!")
#        abort(404,description="Access denied!")
        return redirect(url_for('index'))

@module002.route('/post/<course>', methods=['GET','POST'])
@login_required
def module002_post(course):
    form = PostForm()
    course_query = Course.query.filter_by(name=course).first()
    if request.method == 'POST':
        if form.validate_on_submit():
            post = Post(body=form.body.data, author_id=current_user.id, course_id=course_query.id)
            db.session.add(post)
            db.session.commit()
            flash("Mensaje envidado con exito!")

            posts = Post.query.filter_by(course_id=course_query.id).order_by(Post.timestamp.desc())

    else:
        posts = Post.query.filter_by(course_id=course_query.id).order_by(Post.timestamp.desc())


    follows = Follow.query.filter_by(user_id=current_user.id)
    return render_template("module002_post.html",module="module002", form=form, rows=posts, routes=follows, course=course)



@module002.route('/test')
def module002_test():
    return 'OK'

module002/templates/module002_index.html
{% extends 'base.html' %}

{% block content %}

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
                <li><a href="{{url_for('module002.module002_index')}}">Home</a></li>
              {% for route in routes %}
                <li><a href={{url_for('module002.module002_post', course=route.course_name) }}>{{ route.course_name }}</a></li>
              {% endfor %}

          </ul>
        </div>
      </div>
    </div>

{% endblock %}

module002/templates/module002_post.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div>

    <div class="container-fluid" style="float: left;">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar" style="width: 290px;">
                <li><a href={{url_for('module002.module002_index')}}>Home</a></li>
              {% for route in routes %}
                <li><a href={{url_for('module002.module002_post', course=route.course_name) }}>{{ route.course_name }}</a></li>
              {% endfor %}

          </ul>
        </div>
      </div>
    </div>

    <div>

        <h1 style="text-align: center;">{{ course }}</h1>
        <!-- form -->
        <div class="container justify-content-center">
          <form class="form-signin" method="POST" action="{{ url_for('module002.module002_post', course=course) }}">
            <h2 class="form-signin-heading"> Post </h2>
            {{ form.hidden_tag() }}
        	{{ wtf.form_field(form.body) }}
           <button class="btn btn-lg btn-primary btn-block" type="submit"> Post </button>
         </form>

        <div>
                <table class="table table-striped">
                  <thead>
                    <tr>

                      <th>Messages</th>

                    </tr>
                  </thead>
                  <tbody>
                    {% for row in rows %}
                    <tr>
                        <td>
                            <p style="color:#286090;font-size:18px;">{{ row.author.username }}</p>
                            <p>{{ row.body }}</p>
                        </td>
                        <td style="min-width:100px;vertical-align:bottom;">{{ row.timestamp }}</td>

                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>

      </div> <!-- /container -->



    </div>





</div>




{% endblock %}