module003/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, DateTimeField, SelectField, HiddenField, TextAreaField, SubmitField
from wtforms.validators import InputRequired, Length
from wtforms.fields.html5 import DateField, TimeField, DateTimeLocalField
import datetime


class AssignmentCreateForm(FlaskForm):
    title = StringField('Assignment title',validators=[Length(max=50)])
    description = TextAreaField('Task Description')
    course_id = SelectField('Course (must create a library first)', choices = [], validators = [InputRequired()])
    date_expire = DateField('Choose an expiring date',format='%Y-%m-%d', default=datetime.datetime.today)
    time_expire = TimeField('Expiring time',format='%H:%M', default=datetime.time(23, 59))

class GradeForm(FlaskForm):
    grade = StringField('Update Grade',validators=[Length(max=50)])

module003/views.py
from application import get_app
from flask_login import login_required, login_user, logout_user, current_user
from flask import render_template, request, redirect, url_for, flash, Blueprint, send_file, Response
from sqlalchemy import or_
from models import User, get_db, Course, Assignment, Follow, AssignmentSubmit
import datetime
from io import BytesIO
from werkzeug import FileWrapper


db = get_db()

from module003.forms import *

module003 = Blueprint("module003", __name__,static_folder="static",template_folder="templates")

@module003.route('/')
def module003_index():
    return render_template("module003_index.html",module='module003')


@module003.route('/create', methods=['GET', 'POST'])
def module003_create():
    form = AssignmentCreateForm()

    if request.method == 'POST':
        try:
            course = Course.query.get(form.course_id.data)
            assignment = Assignment(title = form.title.data,
                    body = form.description.data,
                    date_expire = datetime.datetime.combine(form.date_expire.data, form.time_expire.data),
                    course_id = course.id,
                    course_name = course.name,
                    institution_name = course.institution_name,
                    user_id=current_user.id)

            db.session.add(assignment)
            db.session.commit()
            flash("Tarea creda con exito")

        except:
            flash("Error creando tarea")


    for course in Course.query.filter_by(user_id=current_user.id):
        form.course_id.choices += [(course.id,  str(course.id) + ' - ' + course.institution_name + ' - ' + course.name)]

    assignments = Assignment.query.filter(Assignment.user_id==current_user.id)

    return render_template("module003_create.html",module='module003', form=form, rows=assignments)

@module003.route('/submit', methods=['GET', 'POST'])
def module003_submit():

    assignments = Assignment.query.join(Follow, Assignment.course_id == Follow.course_id).filter(Follow.user_id == current_user.id)

    submitted = []

    for assignment in assignments:
        if AssignmentSubmit.query.filter(AssignmentSubmit.assignment_id == assignment.id, AssignmentSubmit.user_id == current_user.id).count() >= 1:
            submitted.append("Si")

        else:
            submitted.append("No")


    return render_template("module003_submit.html",module='module003', rows=assignments , submitted=submitted)


@module003.route('/submit/<assignmentid>', methods=['GET', 'POST'])
def module003_submit_id(assignmentid):

    assignment = Assignment.query.filter(Assignment.id == assignmentid).first()

    if request.method == 'POST':
        try:

            assignmentquery = Assignment.query.filter(Assignment.id == assignmentid).first()

            assignment_submit = AssignmentSubmit(course_name=assignmentquery.course_name,
                                    institution_name = assignmentquery.institution_name,
                                    data = request.files['inputFile'].read(),
                                    grade = "-",
                                    assignment_id = assignmentid,
                                    user_id = current_user.id,
                                    course_id = assignmentquery.course_id)

            db.session.add(assignment_submit)
            db.session.commit()
            flash("Tarea entregada con exito")

            return redirect(url_for('module003.module003_submit'))

        except Exception as e:
            print(e)
            flash("Error entregando tarea")

    rows =  AssignmentSubmit.query.filter(AssignmentSubmit.assignment_id == assignment.id, AssignmentSubmit.user_id == current_user.id)

    return render_template("module003_submit_id.html",module='module003', rows=rows , assignment=assignment)



@module003.route('/grade', methods=['GET', 'POST'])
def module003_grade():

    submits = AssignmentSubmit.query.filter(AssignmentSubmit.assignment_id == request.args['rowid'])

    return render_template("module003_grade.html",module='module003', rows = submits)

@module003.route('/grade/<gradeid>', methods=['GET', 'POST'])
def module003_grade_id(gradeid):

    form = GradeForm()

    if request.method == 'POST':
        submit = AssignmentSubmit.query.get(gradeid)
        submit.grade = form.grade.data
        db.session.commit()

    submit = AssignmentSubmit.query.get(gradeid)

    return render_template("module003_grade_id.html",module='module003', form = form, submit = submit )

@module003.route('/download/<gradeid>', methods=['POST'])
def module003_download(gradeid):

    submit = AssignmentSubmit.query.get(gradeid)
    file = FileWrapper(BytesIO(submit.data))
    return Response(file, mimetype="application/zip" , direct_passthrough=True)

    #return send_file(BytesIO(submit.data),  mimetype='application/zip', attachment_filename="Hola.zip" , as_attachment=True)



@module003.route('/test')
def module003_test():
    return 'OK'

module003/templates/module003_create.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div>

    <div class="container-fluid" style="float: left;">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar" style="width: 290px;">
                <li><a href="{{url_for('module003.module003_index')}}">Home</a></li>
                <li><a href="{{url_for('module003.module003_create')}}">Create assignment</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container justify-content-center">
          <form class="form-signin" method="POST" action="{{ url_for('module003.module003_create', course=course) }}">
            <h2 class="form-signin-heading"> Create Assignment </h2>
            {{ form.hidden_tag() }}
        	{{ wtf.form_field(form.title) }}
        	{{ form.hidden_tag() }}
        	{{ wtf.form_field(form.description) }}
        	{{ form.hidden_tag() }}
        	{{ wtf.form_field(form.course_id) }}
        	{{ form.hidden_tag() }}
        	{{ wtf.form_field(form.date_expire) }}
        	{{ form.hidden_tag() }}
        	{{ wtf.form_field(form.time_expire) }}

           <button class="btn btn-lg btn-primary btn-block" type="submit"> Post </button>
         </form>

    <div>

    <div class="table-responsive">
        <table id="myTable" class="table table-striped">
          <thead>
            <tr>
              <th>Edit</th>
              <th>Title</th>
              <th>Description</th>
              <th>Course Name</th>
              <th>Institution Name</th>
              <th>Expiring Date</th>
              <th>Date Created</th>
              <th>Date Modified</th>
            </tr>
          </thead>
          <tbody>
            {% for row in rows %}
            <tr>


               <td> <a><form action="{{url_for('module001.module001_participation_generate')}}" method="GET">
                   <input type="submit" value={{ row.id }} name="rowid">
               </form> </a></td>
                <td>{{ row.title }}</td>
                <td>{{ row.body }}</td>
                <td>{{ row.course_name }}</td>
                <td>{{ row.institution_name }}</td>
                <td>{{ row.date_expire }}</td>
                <td>{{ row.date_created }}</td>
                <td>{{ row.date_modified }}</td>

            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

</div>

{% endblock %}

module003/templates/module003_grade.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div>

    <div class="container-fluid" style="float: left;">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar" style="width: 290px;">
                <li><a href="{{url_for('module003.module003_index')}}">Home</a></li>
                <li><a href="{{url_for('module003.module003_create')}}">Create assignment</a></li>
                <li><a href="{{url_for('module003.module003_submit')}}">Submit assignment</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container justify-content-center">

        <div class="table-responsive">
            <table id="myTable" class="table table-striped">
              <thead>
                <tr>
                    <th>User</th>
                    <th>Date submitted</th>
                    <th>Grade assignment</th>
                </tr>
              </thead>
              <tbody>
                {% for row in rows %}
                <tr>
                    <td>{{ row.username.username }}</td>
                    <td>{{ row.date_submitted }}</td>
                    <td> <a><form action="{{ url_for('module003.module003_grade_id', gradeid=row.id) }}">
                        <input type="submit" value={{ row.id }}>
                    </form> </a></td>

                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>


    </div>




</div>

{% endblock %}

module003/templates/module003_grade_id.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div>

    <div class="container-fluid" style="float: left;">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar" style="width: 290px;">
                <li><a href="{{url_for('module003.module003_index')}}">Home</a></li>
                <li><a href="{{url_for('module003.module003_create')}}">Create assignment</a></li>
                <li><a href="{{url_for('module003.module003_submit')}}">Submit assignment</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container justify-content-center">

        <h1>User: {{ submit.username.username }}</h1>

        <h2>Date submitted: {{ submit.date_submitted }}</h2>

        <h2>Grade: {{ submit.grade }}/10</h2>

        <h2>Download content: </h2>
        <a><form method="POST" action="{{ url_for('module003.module003_download', gradeid=submit.id) }}">
                   <input type="submit" value="download">
        </form> </a>

        <hr>

        <form style="width:150px" class="form-signin" method="POST" action="{{ url_for('module003.module003_grade_id', gradeid=submit.id) }}">
                {{ form.hidden_tag() }}
                {{ wtf.form_field(form.grade) }}
            <button class="btn btn-lg btn-primary btn-block" type="submit">> Update </button>
        </form>

    </div>



</div>

{% endblock %}

module003/templates/module003_index.html
{% extends 'base.html' %}

{% block content %}
	<div class="container-fluid" style="float: left;">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar" style="width: 290px;">
                <li><a href="{{url_for('module003.module003_index')}}">Home</a></li>
                <li><a href="{{url_for('module003.module003_create')}}">Create assignment</a></li>
                <li><a href="{{url_for('module003.module003_submit')}}">Submit assignment</a></li>
          </ul>
        </div>
      </div>
    </div>
{% endblock %}

module003/templates/module003_submit.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div>

    <div class="container-fluid" style="float: left;">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar" style="width: 290px;">
                <li><a href="{{url_for('module003.module003_index')}}">Home</a></li>
                <li><a href="{{url_for('module003.module003_create')}}">Create assignment</a></li>
                <li><a href="{{url_for('module003.module003_submit')}}">Submit assignment</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container justify-content-center">

        <h1>Submit an assignment</h1>

        <div class="table-responsive">
        <table id="myTable" class="table table-striped">
          <thead>
            <tr>
              <th> </th>
              <th>Title</th>
              <th>Description</th>
              <th>Course Name</th>
              <th>Institution Name</th>
              <th>Expiring Date</th>
              <th>Submitted</th>
            </tr>
          </thead>
          <tbody>
            {% for row in rows %}
            <tr>


               <td> <a><form action="{{ url_for('module003.module003_submit_id', assignmentid=row.id) }}">
                   <input type="submit" value="Submit">
               </form> </a></td>
                <td>{{ row.title }}</td>
                <td>{{ row.body }}</td>
                <td>{{ row.course_name }}</td>
                <td>{{ row.institution_name }}</td>
                <td>{{ row.date_expire }}</td>
                <td>{{ submitted[loop.index0] }}</td>

            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>



    </div>


</div>

{% endblock %}

module003/templates/module003_submit_id.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div>

    <div class="container-fluid" style="float: left;">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar" style="width: 290px;">
                <li><a href="{{url_for('module003.module003_index')}}">Home</a></li>
                <li><a href="{{url_for('module003.module003_create')}}">Create assignment</a></li>
                <li><a href="{{url_for('module003.module003_submit')}}">Submit assignment</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container justify-content-center">

        <h1>{{ assignment.title }}</h1>
        <p1>{{ assignment.body }}</h1>
        </br>
        <div>
            <form method="POST" action="" enctype="multipart/form-data">
                <label for="inputFile">File Input</label>
                <input type="file" name="inputFile">
                </br>
                <button type="submit" class="btn btn-lg btn-primary btn-block">Submit</button>
            </form>
        </div>

        </br>

        <div class="table-responsive">
        <table id="myTable" class="table table-striped">
          <thead>
            <tr>
              <th>id</th>
              <th>Date Submitted</th>
              <th>Grade</th>
            </tr>
          </thead>
          <tbody>
            {% for row in rows %}
            <tr>
                <td>{{ row.id }}</td>
                <td>{{ row.date_submitted }}</td>
                <td>{{ row.grade }}/10</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

    </div>




    </div>





</div>

{% endblock %}